### ISSUE TITLE
kernel 5.18.1 编译失败

### ISSUE THREAD

**Issue by lexiaoyao12138** [HRex39/rtl8852be#5]
uname -a `Linux archlinux 5.18.1-arch1-1`
--- 

**error**:
```
#rm -f .symvers.8852be
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.18.1-arch1-1/build M=/home/dong/code/rtl8852be  modules
make[1]: 进入目录“/usr/lib/modules/5.18.1-arch1-1/build”
  CC [M]  /home/dong/code/rtl8852be/platform/platform_linux_pc_pci.o
  CC [M]  /home/dong/code/rtl8852be/os_dep/osdep_service.o
  CC [M]  /home/dong/code/rtl8852be/os_dep/osdep_service_linux.o
  CC [M]  /home/dong/code/rtl8852be/os_dep/linux/rtw_cfg.o
  CC [M]  /home/dong/code/rtl8852be/os_dep/linux/os_intfs.o
  CC [M]  /home/dong/code/rtl8852be/os_dep/linux/ioctl_linux.o
  CC [M]  /home/dong/code/rtl8852be/os_dep/linux/xmit_linux.o
  CC [M]  /home/dong/code/rtl8852be/os_dep/linux/mlme_linux.o
/home/dong/code/rtl8852be/os_dep/linux/os_intfs.c: 在函数‘rtw_net_set_mac_address’中:
/home/dong/code/rtl8852be/os_dep/linux/os_intfs.c:79:28: 警告：passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   79 |         _rtw_memcpy(pnetdev->dev_addr, sa->sa_data, ETH_ALEN); /* set mac addr to net_device */
      |                     ~~~~~~~^~~~~~~~~~
In file included from /home/dong/code/rtl8852be/include/drv_types.h:25,
                 from /home/dong/code/rtl8852be/os_dep/linux/os_intfs.c:17:
/home/dong/code/rtl8852be/include/osdep_service.h:281:24: 附注：需要类型‘void *’，但实参的类型为‘const unsigned char *’
  281 | void _rtw_memcpy(void *dec, const void *sour, u32 sz);
      |                  ~~~~~~^~~
/home/dong/code/rtl8852be/os_dep/osdep_service_linux.c: 在函数‘rtw_change_ifname’中:
/home/dong/code/rtl8852be/os_dep/osdep_service_linux.c:810:28: 警告：passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  810 |         _rtw_memcpy(pnetdev->dev_addr, adapter_mac_addr(padapter), ETH_ALEN);
      |                     ~~~~~~~^~~~~~~~~~
/home/dong/code/rtl8852be/os_dep/osdep_service_linux.c:48:24: 附注：需要类型‘void *’，但实参的类型为‘const unsigned char *’
   48 | void _rtw_memcpy(void *dst, const void *src, u32 sz)
      |                  ~~~~~~^~~
/home/dong/code/rtl8852be/os_dep/linux/os_intfs.c: 在函数‘rtw_os_ndev_register’中:
/home/dong/code/rtl8852be/os_dep/linux/os_intfs.c:623:25: 警告：passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  623 |         _rtw_memcpy(ndev->dev_addr, adapter_mac_addr(adapter), ETH_ALEN);
      |                     ~~~~^~~~~~~~~~
/home/dong/code/rtl8852be/include/osdep_service.h:281:24: 附注：需要类型‘void *’，但实参的类型为‘const unsigned char *’
  281 | void _rtw_memcpy(void *dec, const void *sour, u32 sz);
      |                  ~~~~~~^~~
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c: 在函数‘pci_cache_wback’中:
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c:21:17: 错误：implicit declaration of function ‘pci_dma_sync_single_for_device’; did you mean ‘dma_sync_single_for_device’? [-Werror=implicit-function-declaration]
   21 |                 pci_dma_sync_single_for_device(hwdev, *bus_addr, size,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 dma_sync_single_for_device
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c: 在函数‘pci_cache_inv’中:
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c:30:17: 错误：implicit declaration of function ‘pci_dma_sync_single_for_cpu’; did you mean ‘dma_sync_single_for_cpu’? [-Werror=implicit-function-declaration]
   30 |                 pci_dma_sync_single_for_cpu(hwdev, *bus_addr, size, direction);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 dma_sync_single_for_cpu
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c: 在函数‘pci_get_bus_addr’中:
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c:39:29: 错误：implicit declaration of function ‘pci_map_single’; did you mean ‘dma_map_single’? [-Werror=implicit-function-declaration]
   39 |                 *bus_addr = pci_map_single(hwdev, vir_addr, size, direction);
      |                             ^~~~~~~~~~~~~~
      |                             dma_map_single
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c: 在函数‘pci_unmap_bus_addr’中:
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c:50:17: 错误：implicit declaration of function ‘pci_unmap_single’; did you mean ‘dma_unmap_single’? [-Werror=implicit-function-declaration]
   50 |                 pci_unmap_single(hwdev, *bus_addr, size, direction);
      |                 ^~~~~~~~~~~~~~~~
      |                 dma_unmap_single
  CC [M]  /home/dong/code/rtl8852be/os_dep/linux/recv_linux.o
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c: 在函数‘pci_free_noncache_mem’中:
/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.c:97:17: 错误：隐式声明函数‘pci_free_consistent’ [-Werror=implicit-function-declaration]
   97 |                 pci_free_consistent(pdev, size, vir_addr, *bus_addr);
      |                 ^~~~~~~~~~~~~~~~~~~
  CC [M]  /home/dong/code/rtl8852be/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /home/dong/code/rtl8852be/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /home/dong/code/rtl8852be/os_dep/linux/wifi_regd.o
cc1：有些警告被当作是错误
make[2]: *** [scripts/Makefile.build:288：/home/dong/code/rtl8852be/platform/platform_linux_pc_pci.o] 错误 1
make[2]: *** 正在等待未完成的任务....
/home/dong/code/rtl8852be/os_dep/linux/ioctl_cfg80211.c: 在函数‘rtw_get_chbwoff_from_cfg80211_chan_def’中:
/home/dong/code/rtl8852be/os_dep/linux/ioctl_cfg80211.c:6233:21: 警告：this statement may fall through [-Wimplicit-fallthrough=]
 6233 |                 *ht = 0;
      |                 ~~~~^~~
/home/dong/code/rtl8852be/os_dep/linux/ioctl_cfg80211.c:6235:9: 附注：here
 6235 |         case NL80211_CHAN_WIDTH_20:
      |         ^~~~
make[1]: *** [Makefile:1834：/home/dong/code/rtl8852be] 错误 2
make[1]: 离开目录“/usr/lib/modules/5.18.1-arch1-1/build”
make: *** [Makefile:637：modules] 错误 2
```

**Comment by HRex39** [comment]
This seems to be due to a change in the API interface. 
Try changing "pci_" to "dma_" might fix the problem?

**Comment by HRex39** [comment]
Every time the kernel is updated, there is an API interface change, and then all drivers have to be changed. This is arch Linux?

**Comment by Phosphenius** [comment]
I've experienced the same problem yesterday on Arch Linux. With the LTS kernel (5.15), it does work perfectly fine though.

Maybe I can look into these API changes when I find some time for it, but that won't be in the next 10 days.

**Comment by lexiaoyao12138** [comment]
> 每次更新内核时，都会有一个API接口更改，然后所有驱动程序都必须更改。这是 arch Linux？

> Yes, this is archlinux. After upgrading the kernel to 5.18.1 yesterday, the compilation failed. Now it has been downgraded to 5.17.9. As I am not familiar with this knowledge, this question is for your reference.

**Comment by lexiaoyao12138** [comment]
> Every time the kernel is updated, there is an API interface change, and then all drivers have to be changed. This is arch Linux?

> Yes, this is archlinux. After upgrading the kernel to 5.18.1 yesterday, the compilation failed. Now it has been downgraded to 5.17.9. As I am not familiar with this knowledge, this question is for your reference.

**Comment by HRex39** [comment]
@Phosphenius @lexiaoyao12138 
[Ref1](https://github.com/Suraj-Upadhyay/dev-linux/blob/master/include/linux/pci-dma-compat.h)
[Ref2](https://github.com/Suraj-Upadhyay/dev-linux/issues/6)
Theoretically, by changing this API, the code can adapt to the latest kernel (I think), but more tests are needed

**Comment by HRex39** [comment]
I have just push a new version on "dev" branch, hope you test for it when available, thanks.

**Comment by HRex39** [comment]
I have just build it successfully using kernel```5.18.0-1-MANJARO```, with "a fair amount of compiler warnings", expect more hardware testing and feedback.

**Comment by Phosphenius** [comment]
Thank you so much! Your work is very much appreciated. 

I can now successfully build against `5.18.1-arch1-1` and so far the WiFi is working perfectly with some occasional errors showing up in `dmesg`.

**Comment by HRex39** [comment]
> Thank you so much! Your work is very much appreciated.
> 
> I can now successfully build against `5.18.1-arch1-1` and so far the WiFi is working perfectly with some occasional errors showing up in `dmesg`.

Did you mean ```_rtw_memcpy(pnetdev->dev_addr, mac, ETH_ALEN);```   
That‘s an existing bug, I’ll check it out, any ideas are welcomed.

**Comment by HRex39** [comment]
Actually, The latest update on code(with a mount of ```#ifdef```) looks ugly. I truly believe the newer kernel (>5.18) delete the ‘’pci-dma-compat.h’’ , but I’m not sure since other network repo didn’t bring out related  issue.

**Comment by HRex39** [comment]
> Actually, The latest update on code(with a mount of `#ifdef`) looks ugly. I truly believe the newer kernel (>5.18) delete the ‘’pci-dma-compat.h’’ , but I’m not sure since other network repo didn’t bring out related issue.

Alright, the API change is here.  
[https://github.com/torvalds/linux/commit/a2e759612e5ff3858856fe97be5245eecb84e29b](https://github.com/torvalds/linux/commit/a2e759612e5ff3858856fe97be5245eecb84e29b)
